# wrangler.toml
name = "backend-site-marie-emeraude"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "TRANSLATIONS"
id = "9ec708b6ccbc43ce9a5bad9f153b8430"

[vars]
# Ces variables seront publiques, utilisez secrets pour les clés sensibles